name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'

categories:
  - title: '🚀 Features'
    labels: [feature, enhancement]
  - title: '🐛 Bug Fixes'
    labels: [fix, bug]
  - title: '📝 Documentation'
    labels: [documentation]
  - title: '🧰 Maintenance'
    labels: [chore, maintenance, dependencies]

change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&'

version-resolver:
  major:
    labels: [major, breaking]
  minor:
    labels: [minor, feature, enhancement]
  patch:
    labels: [patch, fix, bug, chore, dependencies, documentation]
  default: patch

autolabeler:
  - label: documentation
    files: ['**/*.md', 'docs/**', 'blog/**']
    title: ['/^docs/i']
  - label: bug
    title: ['/^fix/i']
    branch: ['/^fix\//']
  - label: enhancement
    title: ['/^feat/i']
    branch: ['/^feat\//', '/^feature\//']
  - label: dependencies
    title: ['/^build\(deps\)/i', '/bump /i']

template: |
  ## What's changed

  $CHANGES

  **Full changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION
